Numpy is a built in module which stands for Numerical Python

In [2]:
import numpy as np #np is the alias name for numpy

In [3]:
my_list=[12,13,14,15,16]

In [7]:
print(my_list)

[12, 13, 14, 15, 16]


In [4]:
type(my_list)

list

In [5]:
#convert the list into array
arr=np.array(my_list) #.array will convert the list into an array

In [6]:
print(arr)

[12 13 14 15 16]


In [9]:
type(arr) #n dimentional array, here n=1 so we have 1D Array

numpy.ndarray

In [10]:
new_list=['Ankesh','Pramod','Ravi','Tushar']

In [13]:
print(new_list)

['Ankesh', 'Pramod', 'Ravi', 'Tushar']


In [11]:
arr_2=np.array(new_list)

In [12]:
print(arr_2)

['Ankesh' 'Pramod' 'Ravi' 'Tushar']


In [14]:
#multinested array  - array inside array
my_list=[12,13,14,15,16]
my_list_1=[1,15,20,28,16]
my_list_2=[16,56,78,110,22]

arr_new=np.array([my_list,my_list_1,my_list_2]) #multinested array

In [15]:
print(arr_new)

[[ 12  13  14  15  16]
 [  1  15  20  28  16]
 [ 16  56  78 110  22]]


In [16]:
arr_new.shape #.shape gives us the number of rows and columns, we have 2D Array

(3, 5)

In [19]:
arr_new.reshape(5,3) #5 is the number of rows and 3 is the number of columns

array([[ 12,  13,  14],
       [ 15,  16,   1],
       [ 15,  20,  28],
       [ 16,  16,  56],
       [ 78, 110,  22]])

In [20]:
#indexing and slicing
print(arr)

[12 13 14 15 16]


In [21]:
arr[2] #element at 2nd index position will be fetched - 14

14

In [23]:
arr[-3]

14

In [24]:
arr[1:4] #elements from 1st till 3rd index position will be fetched - [13,14,15]

array([13, 14, 15])

In [25]:
print(arr_new)

[[ 12  13  14  15  16]
 [  1  15  20  28  16]
 [ 16  56  78 110  22]]


In [26]:
arr_new[1:,3:]

array([[ 28,  16],
       [110,  22]])

In [27]:
arr_new[0:,2:]

array([[ 14,  15,  16],
       [ 20,  28,  16],
       [ 78, 110,  22]])